
// auth
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

// protected-data
export const GET_NUTRITION_DATA_SUCCESS = 'GET_NUTRITION_DATA_SUCCESS';
export const GET_EXERCISE_DATA_SUCCESS = 'GET_EXERCISE_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';
export const ADD_NUTRITION_DATA_SUCCESS = 'ADD_NUTRITION_DATA_SUCCESS';
export const ADD_EXERCISE_DATA_SUCCESS = 'ADD_EXERCISE_DATA_SUCCESS';
export const ADD_DATA_ERROR = 'ADD_DATA_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const DELETE_DATA_START = 'DELETE_DATA_START';
export const DELETE_NUTRITION_DATA_SUCCESS = 'DELETE_NUTRITION_DATA_SUCCESS';
export const DELETE_EXERCISE_DATA_SUCCESS = 'DELETE_EXERCISE_DATA_SUCCESS';
export const DELETE_DATA_ERROR = 'DELETE_DATA_ERROR';
export const RESET_DELETE = 'RESET_DELETE';

// search 
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const NUTRITION_SEARCH_SUCCESS = 'NUTRITION_SEARCH_SUCCESS';
export const EXERCISE_SEARCH_SUCCESS = 'EXERCISE_SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const CLEAR_SEARCH_ERROR = 'CLEAR_SEARCH_ERROR';

// users
export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const CLEAR_CREATE_USER_ERROR = 'CLEAR_CREATE_USER_ERROR';